[package]
name = "codesage-embed"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
cuda = ["ort/cuda"]

[dependencies]
codesage-protocol.workspace = true
serde.workspace = true
anyhow.workspace = true
tokenizers.workspace = true
hf-hub.workspace = true
tracing.workspace = true
wait-timeout = "0.2"

[target.'cfg(not(target_vendor = "apple"))'.dependencies]
ort = { version = "2.0.0-rc.12", features = ["load-dynamic", "preload-dylibs"] }

[target.'cfg(target_vendor = "apple")'.dependencies]
ort = { version = "2.0.0-rc.12", features = ["coreml"] }